### ISSUE TITLE
启动卡住

### ISSUE THREAD

**Issue by 1677009187** [greenday12138/AUTO#2]
请问卡在这个画面怎么办，显示INFO: Carla server connected
![c6fa91d5-eadb-4ffe-8bab-0bfdd84baca4](https://github.com/greenday12138/AUTO/assets/63623148/c206c88f-0a48-49e3-a824-ed0219c08713)

**Comment by greenday12138** [comment]
This is because the Carla Server crashed (due to bugs related to Unreal Engine), and currently there is no viable solution. The only option is to restart Carla. We plan to add an automatic restart feature in the future.

**Comment by 1677009187** [comment]
OK, thank you for your generous answer
